# Generated by Django 2.0.6 on 2018-08-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('LAWYER', 'Lawyer'), ('GUEST', 'Guest')], default=2, max_length=6),
            preserve_default=False,
        ),
    ]
