# Generated by Django 2.0.6 on 2018-08-09 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20180808_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('CRIMINAL', 'Criminal'), ('EMPLOYMENT', 'Employment'), ('CORPORATE', 'Corporate')], db_index=True, max_length=10)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('name_slug', models.SlugField(max_length=100)),
                ('category_slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=200)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('category_name',),
            },
        ),
        migrations.AlterIndexTogether(
            name='lawyer',
            index_together={('id', 'category_slug')},
        ),
    ]
