# Generated by Django 2.0.6 on 2018-08-09 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180808_0000'),
        ('lawyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('CRIMINAL', 'Criminal'), ('EMPLOYMENT', 'Employment'), ('CORPORATE', 'Corporate')], db_index=True, max_length=10)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('city', models.CharField(max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('category_name',),
            },
        ),
        migrations.AlterModelOptions(
            name='lawyer',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='lawyer',
            old_name='category_slug',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='lawyer',
            name='image',
            field=models.ImageField(blank=True, upload_to='lawyerdp/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='accounts.Profile'),
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='name_slug',
        ),
        migrations.AddField(
            model_name='lawyer',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer', to='lawyer.Category'),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='lawyer',
            index_together={('id', 'slug')},
        ),
    ]
