# Generated by Django 2.0.6 on 2018-08-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0002_auto_20180809_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='image',
        ),
    ]
